name: Helpdesk
version: 1.0
main: com.guzzipirate.helpdesk.Helpdesk
api-version: 1.13
author: Guzzipirate
commands:
  support:
    description: Get help from a staff member
    usage: /<command> [report|request|register] [message]